# Generated by Django 4.2.6 on 2023-10-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_cuantitative', models.BooleanField()),
                ('is_decimal', models.BooleanField()),
                ('is_custom', models.BooleanField()),
                ('unit_of_measurement', models.CharField(max_length=64)),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
            ],
        ),
    ]
