# Generated by Django 4.2.6 on 2023-10-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthindicator',
            name='is_custom',
        ),
        migrations.AddField(
            model_name='healthindicator',
            name='medical_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='healthindicator',
            name='unit_of_measurement',
            field=models.CharField(max_length=16),
        ),
    ]
