# Generated by Django 4.2.6 on 2023-10-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_remove_healthindicator_is_custom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthindicator',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
