# Generated by Django 4.2.6 on 2023-11-23 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_initial'),
        ('records', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='health_indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='indicators.healthindicator'),
        ),
    ]
