# Generated by Django 4.2.6 on 2023-11-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_healthrecord_health_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='alt_value',
            field=models.FloatField(null=True),
        ),
    ]
